favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5967742
  brandStrength: 1
  lightness: 0.5
  brandColors:
    - '#FFFFFF'
    - '#E8C76E'
    - '#030202'
    - '#777777'
    - '#3A3938'
  rhythmicContrast: 0.4462366
typography_spectrum: 0.8799283
layout_spectrum: 0.2258064
cta:
  bucket: null
  version: null
  domain: null
name: marziafinedining
