layout_spectrum: 0.5645161
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 0.25
  brandColors:
    - '#EBF0FA'
    - '#C6875C'
    - '#87919A'
    - '#E9BD03'
    - '#01050E'
  lightness: 0.5
typography_spectrum: 0.5698925
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: marziafinedining
