name: marziafinedining
favicon: null
layout_spectrum: 0.74855
typography_spectrum: 0.7447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070e1d'
    - '#d1ddec'
    - '#dd9831'
    - '#9e3e13'
    - '#9349bf'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
