name: marziafinedining
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.2043011
  brandStrength: 0.2508961
  lightness: 0.327957
  brandColors:
    - '#FFFFFF'
    - '#E8C76E'
    - '#030202'
    - '#777777'
    - '#3A3938'
  rhythmicContrast: 0
typography_spectrum: 0.8799283
layout_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
