name: marziafinedining
favicon: null
layout_spectrum: 0.23988
typography_spectrum: 0.49615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf0fa'
    - '#d1b9b2'
    - '#f5b53b'
    - '#b77047'
    - '#cf8b64'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
