name: marziafinedining
favicon: null
layout_spectrum: 0.5645161
typography_spectrum: 0.5250896
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D5DEE5'
    - '#6B3E07'
    - '#9EA7AE'
    - '#000B01'
    - '#74829C'
  brandStrength: 0.1989247
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
